### ISSUE TITLE
ChangeSelect event does not fire if the fstlist is larger than the max-height

### ISSUE THREAD

**Issue by chahid7** [VirtusX/fstdropdown#8]
Hello,
I am facing an issue with large list that makes the fstlist height > 200px (max-height) and create the scroll-bar, the changeSelect event does not fire, instead the blur event fires and nothing is selected.
So if we have a scrollbar in the options list, we can not select.
Thank you for your help

**Comment by zgood-dev** [comment]
Check and see if you also have this issue in FireFox or another browser - it might not be related to the list height, but rather how events propagate in Chrome.

I just solved a similar problem where users could not select anything from the dropdown list - but only Chrome (probably because of a recent Chrome update) and we have not updated anything on the site for over 6 months.

I had to completely remove the blur event from the dropdown and that fixed the issue. I did this by editing the script in the function "createdropdown" on [line 21](https://github.com/VirtusX/fstdropdown/blob/71bae20e7d5ca9d7891a621cd49e6a4987a9c235/fstdropdown.js#L21) of the source code (completely remove `"blur": openSelect` - the click event is good enough). The problem is that in Chrome the blur event gets triggered when you select an option from the dropdown list, which does trigger and causes the list to close/hide BUT it does not propagate/bubble for the event to fire for the selected option in the list. So the list just closes and nothing will get selected.

I am not 100% sure if this is the same problem you are facing, but it does sound similar. I spend over 5 hours on this problem yesterday.

I would also recommend NOT using this plugin as it is **very poorly written** and I have experience many other issues with it. Our team is currently in the process of removing this library and using a less buggy, better written library like select2. This plugin is the worst dropdown library I have used in my 15+ years as a web developer. Stay away (I created a GitHub account just now to tell you this lol)!

**Comment by marcos987** [comment]
Facing the same issue, removing "blur": openSelect on line 21 did not solve it for me, it was working just fine for years, issue started recently probably due to a chrome update

**Comment by toehead2001** [comment]
I was able to work-around the issue by modifying the `checkEvent` function.

See below where I added `|| event.relatedTarget.className == "fstlist"`

```
    function checkEvent(event, force) {
        return event.relatedTarget != null && (event.relatedTarget.tagName == "INPUT" || (event.relatedTarget.tagName == "BUTTON" && force == undefined))
            || event.target.tagName == "INPUT" && event.type != "blur"
            || event.target.tagName == "INPUT" && (event.relatedTarget != null && event.relatedTarget.classList.contains("fstdropdown") && event.relatedTarget.classList.contains("open"))
            || event.target.classList.contains("fstselected") && event.type == "blur" && document.activeElement.classList.contains("fstsearchinput")
            || event.type == "blur" && (document.activeElement.className == "fstlist" || document.activeElement.className == "fstAll" || event.relatedTarget.className == "fstlist")
            || event.target.tagName == "BUTTON" && force == undefined;
    }
```

**Comment by chahid7** [comment]
Thank you for your replies,
I can confirm that it is related to Chrome only.
I tried to remove the blur event but did not work. 
Same for the '|| event.relatedTarget.className == "fstlist"' it didn't solve the issue. 
I am still searching for a workaround.

Updates: A Chrome update fixed the issue
